name: Update README with Recent Repos

on:
  schedule:
    # - cron: "0 0 * * *" # Runs daily at midnight UTC
    - cron: "* * * * *" # Runs every minute (GitHub minimum is actually every 5 minutes)
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update README with recent repos
        uses: wanglez/recent-repos-readme@v1.0.0
        with:
          github_username: PrajwalDev056
          max_repos: 5
          readme_path: ./README.md
          sort: created

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update recent repositories in README"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
